name       : perl-cpan-meta-check
version    : 0.014
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/L/LE/LEONT/CPAN-Meta-Check-0.014.tar.gz : 28a0572bfc1c0678d9ce7da48cf521097ada230f96eb3d063fcbae1cfe6a351f
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : This module verifies if requirements described in a CPAN::Meta object are present.
description: |
    This module verifies if requirements described in a CPAN::Meta object are present.
builddeps  :
    - perl-test-deep
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
