name       : perl-cpan-meta-check
version    : '0.018'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/L/LE/LEONT/CPAN-Meta-Check-0.018.tar.gz : f619d2df5ea0fd91c8cf83eb54acccb5e43d9e6ec1a3f727b3d0ac15d0cf378a
homepage   : https://metacpan.org/pod/CPAN::Meta::Check
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : CPAN::Meta::Check - Verify requirements in a CPAN::Meta object
description: |
    This module verifies if requirements described in a CPAN::Meta object are present.
builddeps  :
    - perl-test-deep
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
